export const SIGN_UP_VALIDATION = 'SIGN_UP_VALIDATION';
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const RESET_FORM_SIGN_UP = 'RESET_FORM_SIGN_UP';
export const FETCH_LIST_MOVIE = 'FETCH_LIST_MOVIE';
export const CHECK_LOGIN_USER = 'CHECK_LOGIN_USER';
export const INPUT_LOGIN_USER = 'INPUT_LOGIN_USER';
export const KEY_SEARCH = "KEY_SEARCH";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const VIEW_TRAILER = "VIEW_TRAILER";
export const OPEN_MODAL_TRAILER = "OPEN_MODAL_TRAILER";
export const CLOSE_MODAL_TRAILER = "CLOSE_MODAL_TRAILER";
export const GALLERY_VIEW_MOVIE = "GALLERY_VIEW_MOVIE";
export const SHOW_GROUP_MOVIE_WILL = "SHOW_GROUP_MOVIE_WILL";
export const FETCH_LIST_CINEMA ="FETCH_LIST_CINEMA";
export const FETCH_LIST_CINEMA_BY_SUPPLIER = "FETCH_LIST_CINEMA_BY_SUPPLIER";
export const FETCH_LIST_MOVIE_CINEMA = "FETCH_LIST_MOVIE_CINEMA"








